In [1]:
print("Python Notebook is WORKING")

Python Notebook is WORKING

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('../data/raw/Dataset Dec 2019.csv')

In [4]:
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-12-01 00:00:00 UTC,remove_from_cart,5712790,1487580005268456287,NaN,f.o.x,6.27,576802932,51d85cb0-897f-48d2-918b-ad63965c12dc
1,2019-12-01 00:00:00 UTC,view,5764655,1487580005411062629,NaN,cnd,29.05,412120092,8adff31e-2051-4894-9758-224bfa8aec18
2,2019-12-01 00:00:02 UTC,cart,4958,1487580009471148064,NaN,runail,1.19,494077766,c99a50e8-2fac-4c4d-89ec-41c05f114554
3,2019-12-01 00:00:05 UTC,view,5848413,1487580007675986893,NaN,freedecor,0.79,348405118,722ffea5-73c0-4924-8e8f-371ff8031af4
4,2019-12-01 00:00:07 UTC,view,5824148,1487580005511725929,NaN,NaN,5.56,576005683,28172809-7e4a-45ce-bab0-5efa90117cd5

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3533286 entries, 0 to 3533285
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     str
 1   event_type     str
 2   product_id     int64
 3   category_id    int64
 4   category_code  str
 5   brand          str
 6   price          float64
 7   user_id        int64
 8   user_session   str
dtypes: float64(1), int64(3), str(5)
memory usage: 242.6 MB

In [6]:
df.columns

Index(['event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='str')

In [7]:
df['event_type'].value_counts()

event_type
view                1728331
cart                 927124
remove_from_cart     664655
purchase             213176
Name: count, dtype: int64

In [8]:
df.isnull().sum()

event_time             0
event_type             0
product_id             0
category_id            0
category_code    3474821
brand            1510289
price                  0
user_id                0
user_session         779
dtype: int64

In [9]:
df['user_id'].nunique()

370154

In [10]:
df['product_id'].nunique()

44624

In [11]:
df['event_time']=pd.to_datetime(df['event_time'])

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3533286 entries, 0 to 3533285
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     datetime64[us, UTC]
 1   event_type     str
 2   product_id     int64
 3   category_id    int64
 4   category_code  str
 5   brand          str
 6   price          float64
 7   user_id        int64
 8   user_session   str
dtypes: datetime64[us, UTC](1), float64(1), int64(3), str(4)
memory usage: 242.6 MB

# Initial Data Exploration

This notebook explores customer behaviour data from an ecommerce platform to understand:
- customer activity
- purchase behaviour
- cart abandonment
- retention patterns

In [13]:
df.shape

(3533286, 9)

In [14]:
df.columns

Index(['event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='str')

In [15]:
df.describe()

         product_id   category_id         price       user_id
count  3.533286e+06  3.533286e+06  3.533286e+06  3.533286e+06
mean   5.473054e+06  1.555023e+18  8.871856e+00  5.223318e+08
std    1.331331e+06  1.689262e+17  1.986474e+01  8.494819e+07
min    3.752000e+03  1.487580e+18 -7.937000e+01  1.180452e+06
25%    5.726191e+06  1.487580e+18  2.060000e+00  4.866830e+08
50%    5.811429e+06  1.487580e+18  4.210000e+00  5.566496e+08
75%    5.859462e+06  1.487580e+18  7.140000e+00  5.828019e+08
max    5.917178e+06  2.235524e+18  3.277800e+02  5.954145e+08

In [16]:
df['event_type'].value_counts()

event_type
view                1728331
cart                 927124
remove_from_cart     664655
purchase             213176
Name: count, dtype: int64

In [17]:
df['event_type'].value_counts().sum()

np.int64(3533286)

In [18]:
df['event_type'].value_counts(normalize=True)*100

event_type
view                48.915684
cart                26.239710
remove_from_cart    18.811243
purchase             6.033364
Name: proportion, dtype: float64

In [19]:
df.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
3533281    False
3533282    False
3533283    False
3533284    False
3533285    False
Length: 3533286, dtype: bool

In [20]:
df.duplicated().sum()

np.int64(183860)

In [21]:
df['user_session'].unique()

<StringArray>
['51d85cb0-897f-48d2-918b-ad63965c12dc',
 '8adff31e-2051-4894-9758-224bfa8aec18',
 'c99a50e8-2fac-4c4d-89ec-41c05f114554',
 '722ffea5-73c0-4924-8e8f-371ff8031af4',
 '28172809-7e4a-45ce-bab0-5efa90117cd5',
 '38cf4ba1-4a0a-4c9e-b870-46685d105f95',
 '1512be50-d0fd-4a92-bcd8-3ea3943f2a3b',
 '676d9fcc-2a4f-4448-b49d-136f2e4208c1',
 '8de492d7-0937-47ae-be2c-a7615aec2b0d',
 '006dd2fb-ae1e-4461-985a-d4e70ca64543',
 ...
 'c4be0b46-60ea-4cd0-9a3e-472a51a31f1c',
 '74ca1cd5-5381-4ffe-b00b-a258b390db77',
 '77cb298e-6f3e-4917-aeb4-f08b713115e1',
 '2d8ea6a9-102c-49be-85e3-dc631b584606',
 'be41f181-5de7-8271-70b0-8f492a4ed843',
 'adbdcc0b-82fc-459a-9d31-f9dd9ee6bf68',
 '7e8a2b85-153a-44eb-a71f-b748fde14fcc',
 '5ecf66ed-634c-465e-a6b5-6b601c4fef19',
 '2dde9867-9e71-4a64-880d-aa68b66aae6d',
 '4c6d80bb-5dd3-4fbb-b592-187b51db2753']
Length: 839813, dtype: str

In [22]:
df['user_session'].nunique()

839812

In [23]:
purchases = df[df['event_type']=='purchase']

In [24]:
purchases.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
557,2019-12-01 00:17:50+00:00,purchase,4554,1487580010796548183,NaN,runail,0.38,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
558,2019-12-01 00:17:50+00:00,purchase,4600,1487580010796548183,NaN,runail,0.38,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
559,2019-12-01 00:17:50+00:00,purchase,4607,1487580010796548183,NaN,runail,0.38,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
560,2019-12-01 00:17:50+00:00,purchase,4640,1487580011157258342,NaN,runail,0.37,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
561,2019-12-01 00:17:50+00:00,purchase,4689,1487580010796548183,NaN,runail,0.38,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9

In [25]:
duplicates = df[df.duplicated()]

In [26]:
duplicates.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
37,2019-12-01 00:01:52+00:00,cart,5700046,1487580009286598681,NaN,runail,0.40,576802932,51d85cb0-897f-48d2-918b-ad63965c12dc
55,2019-12-01 00:02:49+00:00,cart,5693501,1487580009445982239,NaN,NaN,0.60,579751441,8de492d7-0937-47ae-be2c-a7615aec2b0d
61,2019-12-01 00:03:08+00:00,remove_from_cart,5859482,1487580005671109489,NaN,masura,1.60,561162056,39cf2227-03ed-421e-9615-7814b9b3c5e6
62,2019-12-01 00:03:08+00:00,remove_from_cart,5839671,1487580005671109489,NaN,masura,2.19,561162056,39cf2227-03ed-421e-9615-7814b9b3c5e6
66,2019-12-01 00:03:10+00:00,remove_from_cart,5859482,1487580005671109489,NaN,masura,1.60,561162056,39cf2227-03ed-421e-9615-7814b9b3c5e6

In [27]:
duplicates.shape

(183860, 9)

In [28]:
duplicates.sample(10)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
3150581,2019-12-26 12:20:02+00:00,remove_from_cart,5813089,1842735760499802745,NaN,kinetics,9.44,587009546,92035d1b-585d-4dad-8e1c-f3eab3536db3
3063325,2019-12-25 14:28:56+00:00,remove_from_cart,5829347,1487580011585077370,NaN,farmstay,0.79,592290581,94e43dd7-a7be-4d46-b96e-2dc555114cc8
2294344,2019-12-18 13:34:23+00:00,remove_from_cart,5683740,1487580005595612013,NaN,NaN,3.00,551761410,14f74893-bd45-42cc-b7c5-62a3b6d838d0
2317577,2019-12-18 17:13:32+00:00,remove_from_cart,5704998,1487580008145748965,NaN,irisk,1.11,422178927,748926d6-d7b3-4d04-bbdc-fc4174e71ca4
1422040,2019-12-11 17:28:08+00:00,remove_from_cart,5847342,1487580005268456287,NaN,NaN,6.98,510369366,0eb3091e-c41f-46df-ab96-0cefaf05cdf2
862223,2019-12-07 17:51:35+00:00,remove_from_cart,5786613,1487580013950664926,NaN,swarovski,14.44,531594447,59d2814e-19cd-4374-bfa2-a901092e28a3
1615923,2019-12-13 05:48:24+00:00,remove_from_cart,5677045,1487580008246412266,NaN,estel,7.70,582698135,83512b81-2b53-4426-bc89-4269940046ac
387804,2019-12-03 20:49:13+00:00,remove_from_cart,5900465,2151191071378375538,NaN,NaN,4.76,505239648,9918a6af-3adc-4bdf-aa89-bf96435dbbc3
2807596,2019-12-23 10:13:10+00:00,remove_from_cart,5843548,1487580010628776014,NaN,NaN,3.97,505640840,07d77f66-299c-449f-9b2b-8f4c95ce71e5
695345,2019-12-06 09:04:23+00:00,remove_from_cart,5647150,1487580008246412266,NaN,concept,4.60,572590109,ba274ca3-e813-41e6-953f-cfc398d86f8c

In [29]:
duplicates.sort_values(by=['user_id']).head(20)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
2516371,2019-12-20 11:54:26+00:00,cart,5769907,1487580013841613016,NaN,kapous,3.65,12055855,98b129c4-2ab1-4e89-8511-de4bf7f0d943
2516382,2019-12-20 11:54:30+00:00,cart,5769907,1487580013841613016,NaN,kapous,3.65,12055855,98b129c4-2ab1-4e89-8511-de4bf7f0d943
2516375,2019-12-20 11:54:29+00:00,cart,5769907,1487580013841613016,NaN,kapous,3.65,12055855,98b129c4-2ab1-4e89-8511-de4bf7f0d943
3202428,2019-12-27 00:04:35+00:00,remove_from_cart,5570246,1487580011283087468,NaN,NaN,5.56,31156111,7298d4e4-4bbb-4d4f-9cca-c990eedd64c3
1358823,2019-12-11 09:47:16+00:00,remove_from_cart,5677988,1487580010318397504,NaN,estel,6.67,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358711,2019-12-11 09:46:35+00:00,remove_from_cart,5861618,1487580008246412266,NaN,lador,17.97,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358669,2019-12-11 09:46:16+00:00,remove_from_cart,5766581,1487580008263189483,NaN,kaaral,26.08,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358765,2019-12-11 09:46:56+00:00,remove_from_cart,5710657,1487580008246412266,NaN,latinoil,26.19,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358774,2019-12-11 09:46:58+00:00,remove_from_cart,5861602,1783999067156644376,NaN,lador,13.52,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1359064,2019-12-11 09:49:15+00:00,remove_from_cart,5898386,1487580008246412266,NaN,ecolab,1.29,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1359029,2019-12-11 09:48:59+00:00,remove_from_cart,5646670,1487580007986365405,NaN,NaN,13.97,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358884,2019-12-11 09:47:46+00:00,remove_from_cart,5887963,2130081478220972046,NaN,NaN,8.87,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358868,2019-12-11 09:47:42+00:00,remove_from_cart,5887959,2130081478220972046,NaN,NaN,8.87,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358814,2019-12-11 09:47:13+00:00,remove_from_cart,5844009,1487580010318397504,NaN,NaN,5.16,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358620,2019-12-11 09:45:56+00:00,remove_from_cart,5677037,1487580008246412266,NaN,estel,7.70,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358731,2019-12-11 09:46:42+00:00,remove_from_cart,5862225,1487580008246412266,NaN,matrix,9.84,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358870,2019-12-11 09:47:43+00:00,remove_from_cart,5887958,2130081478220972046,NaN,NaN,8.87,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
3203390,2019-12-27 01:16:57+00:00,remove_from_cart,5808547,1487580008313521133,NaN,kapous,3.81,31156111,7298d4e4-4bbb-4d4f-9cca-c990eedd64c3
3203563,2019-12-27 01:26:23+00:00,remove_from_cart,5769849,1487580010318397504,NaN,estel,4.29,31156111,7298d4e4-4bbb-4d4f-9cca-c990eedd64c3
1361616,2019-12-11 10:06:38+00:00,remove_from_cart,5761411,1487580007432717250,NaN,ingarden,2.86,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096

In [30]:
df[df.duplicated(keep=False)].sort_values(by=['user_id']).head(20)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
2516381,2019-12-20 11:54:30+00:00,cart,5769907,1487580013841613016,NaN,kapous,3.65,12055855,98b129c4-2ab1-4e89-8511-de4bf7f0d943
2516374,2019-12-20 11:54:29+00:00,cart,5769907,1487580013841613016,NaN,kapous,3.65,12055855,98b129c4-2ab1-4e89-8511-de4bf7f0d943
2516375,2019-12-20 11:54:29+00:00,cart,5769907,1487580013841613016,NaN,kapous,3.65,12055855,98b129c4-2ab1-4e89-8511-de4bf7f0d943
2516371,2019-12-20 11:54:26+00:00,cart,5769907,1487580013841613016,NaN,kapous,3.65,12055855,98b129c4-2ab1-4e89-8511-de4bf7f0d943
2516382,2019-12-20 11:54:30+00:00,cart,5769907,1487580013841613016,NaN,kapous,3.65,12055855,98b129c4-2ab1-4e89-8511-de4bf7f0d943
2516370,2019-12-20 11:54:26+00:00,cart,5769907,1487580013841613016,NaN,kapous,3.65,12055855,98b129c4-2ab1-4e89-8511-de4bf7f0d943
3203562,2019-12-27 01:26:23+00:00,remove_from_cart,5769849,1487580010318397504,NaN,estel,4.29,31156111,7298d4e4-4bbb-4d4f-9cca-c990eedd64c3
3203518,2019-12-27 01:24:02+00:00,remove_from_cart,5677417,1487580010318397504,NaN,estel,6.75,31156111,7298d4e4-4bbb-4d4f-9cca-c990eedd64c3
1358883,2019-12-11 09:47:46+00:00,remove_from_cart,5887963,2130081478220972046,NaN,NaN,8.87,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358814,2019-12-11 09:47:13+00:00,remove_from_cart,5844009,1487580010318397504,NaN,NaN,5.16,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358812,2019-12-11 09:47:13+00:00,remove_from_cart,5844009,1487580010318397504,NaN,NaN,5.16,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
3203188,2019-12-27 01:02:53+00:00,remove_from_cart,5841718,1487580008187692007,NaN,NaN,1.37,31156111,7298d4e4-4bbb-4d4f-9cca-c990eedd64c3
3203390,2019-12-27 01:16:57+00:00,remove_from_cart,5808547,1487580008313521133,NaN,kapous,3.81,31156111,7298d4e4-4bbb-4d4f-9cca-c990eedd64c3
3203563,2019-12-27 01:26:23+00:00,remove_from_cart,5769849,1487580010318397504,NaN,estel,4.29,31156111,7298d4e4-4bbb-4d4f-9cca-c990eedd64c3
1358730,2019-12-11 09:46:42+00:00,remove_from_cart,5862225,1487580008246412266,NaN,matrix,9.84,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358731,2019-12-11 09:46:42+00:00,remove_from_cart,5862225,1487580008246412266,NaN,matrix,9.84,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358869,2019-12-11 09:47:43+00:00,remove_from_cart,5887958,2130081478220972046,NaN,NaN,8.87,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358868,2019-12-11 09:47:42+00:00,remove_from_cart,5887959,2130081478220972046,NaN,NaN,8.87,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358764,2019-12-11 09:46:56+00:00,remove_from_cart,5710657,1487580008246412266,NaN,latinoil,26.19,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358765,2019-12-11 09:46:56+00:00,remove_from_cart,5710657,1487580008246412266,NaN,latinoil,26.19,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096

In [31]:
df=df.drop_duplicates()

In [32]:
df.shape

(3349426, 9)

In [33]:
duplicates.shape

(183860, 9)

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df.isnull()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,False,False,False,False,True,False,False,False,False
1,False,False,False,False,True,False,False,False,False
2,False,False,False,False,True,False,False,False,False
3,False,False,False,False,True,False,False,False,False
4,False,False,False,False,True,True,False,False,False
...,...,...,...,...,...,...,...,...,...
3533281,False,False,False,False,True,False,False,False,False
3533282,False,False,False,False,True,False,False,False,False
3533283,False,False,False,False,True,True,False,False,False
3533284,False,False,False,False,True,True,False,False,False
3533285,False,False,False,False,True,True,False,False,False

In [36]:
df.isnull().sum()

event_time             0
event_type             0
product_id             0
category_id            0
category_code    3292700
brand            1428211
price                  0
user_id                0
user_session         714
dtype: int64

In [37]:
len(df)

3349426

In [38]:
(df.isnull().sum()/len(df))*100

event_time        0.000000
event_type        0.000000
product_id        0.000000
category_id       0.000000
category_code    98.306396
brand            42.640470
price             0.000000
user_id           0.000000
user_session      0.021317
dtype: float64

In [39]:
df[df['brand'].isnull()].head(20)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
4,2019-12-01 00:00:07+00:00,view,5824148,1487580005511725929,NaN,NaN,5.56,576005683,28172809-7e4a-45ce-bab0-5efa90117cd5
6,2019-12-01 00:00:18+00:00,cart,5629988,1487580009311764506,NaN,NaN,1.19,579966747,1512be50-d0fd-4a92-bcd8-3ea3943f2a3b
10,2019-12-01 00:00:40+00:00,cart,5755170,1487580009387261981,NaN,NaN,2.79,579751441,8de492d7-0937-47ae-be2c-a7615aec2b0d
12,2019-12-01 00:00:45+00:00,cart,5755170,1487580009387261981,NaN,NaN,2.79,579751441,8de492d7-0937-47ae-be2c-a7615aec2b0d
15,2019-12-01 00:00:46+00:00,cart,5755170,1487580009387261981,NaN,NaN,2.79,579751441,8de492d7-0937-47ae-be2c-a7615aec2b0d
21,2019-12-01 00:01:01+00:00,view,5832416,1487580009471148064,NaN,NaN,0.95,576802932,01dbbcc3-b26b-4bed-bce4-1b506725a351
24,2019-12-01 00:01:15+00:00,cart,5904369,1487580007675986893,NaN,NaN,1.59,348405118,722ffea5-73c0-4924-8e8f-371ff8031af4
25,2019-12-01 00:01:16+00:00,view,5881896,1487580011903844485,NaN,NaN,3.63,537197314,1fc5bdf5-a94f-4e5f-8283-215b3fed14c1
30,2019-12-01 00:01:22+00:00,view,5847872,1487580006317032337,NaN,NaN,7.94,576802932,d3809963-53ce-47fd-88c0-21afda8c90ca
31,2019-12-01 00:01:34+00:00,remove_from_cart,5847872,1487580006317032337,NaN,NaN,7.94,576802932,51d85cb0-897f-48d2-918b-ad63965c12dc
34,2019-12-01 00:01:50+00:00,view,5795703,1487580005268456287,NaN,NaN,10.95,556579890,1d94a188-7fa5-4c52-a9fc-99abf8b4838f
39,2019-12-01 00:02:16+00:00,view,5899850,2115334439910245200,NaN,NaN,4.46,538507783,177b9f5a-9ef3-4e11-b31e-6efd86a9bff2
44,2019-12-01 00:02:32+00:00,view,5817700,1487580010821714008,NaN,NaN,0.71,576802932,7df52373-e255-4889-9d68-e05a7f119cca
48,2019-12-01 00:02:40+00:00,view,5800015,1487580005092295511,NaN,NaN,8.89,555150103,66f40972-7d43-4204-877a-32ee1b1df991
54,2019-12-01 00:02:49+00:00,cart,5693501,1487580009445982239,NaN,NaN,0.60,579751441,8de492d7-0937-47ae-be2c-a7615aec2b0d
67,2019-12-01 00:03:12+00:00,cart,5860196,1487580007776650194,NaN,NaN,0.63,579297642,b4a9e242-2322-453a-a0f3-f8217f17ae37
70,2019-12-01 00:03:16+00:00,cart,5826809,1487580009445982239,NaN,NaN,0.63,494077766,c99a50e8-2fac-4c4d-89ec-41c05f114554
71,2019-12-01 00:03:17+00:00,cart,5904747,1487580007675986893,NaN,NaN,1.59,348405118,722ffea5-73c0-4924-8e8f-371ff8031af4
72,2019-12-01 00:03:17+00:00,view,5897920,1783999072332415142,NaN,NaN,6.67,579970736,89386b8a-30da-4f05-a42c-7e4642ee43a4
75,2019-12-01 00:03:25+00:00,view,5771114,1487580005511725929,NaN,NaN,4.27,509636330,4e930dc6-7cf6-419f-8297-1edd6cd20890

In [40]:
purchase_null_brand = df[(df['event_type']=='purchase') & (df['brand'].isnull())]

In [41]:
purchase_null_brand.shape

(91655, 9)

In [42]:
purchases.shape

(213176, 9)

In [43]:
df['brand']=df['brand'].fillna('Unknown Brand')

In [44]:
df['brand'].isnull().sum()

np.int64(0)

In [45]:
df['brand'].head(20)

0             f.o.x
1               cnd
2            runail
3         freedecor
4     Unknown Brand
5            runail
6     Unknown Brand
7          ingarden
8          roubloff
9            runail
10    Unknown Brand
11          metzger
12    Unknown Brand
13          staleks
14           zinger
15    Unknown Brand
16             yoko
17           entity
18         ingarden
19         ingarden
Name: brand, dtype: str

In [46]:
df[(df['event_type']=='purchase')].head(20)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
557,2019-12-01 00:17:50+00:00,purchase,4554,1487580010796548183,NaN,runail,0.38,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
558,2019-12-01 00:17:50+00:00,purchase,4600,1487580010796548183,NaN,runail,0.38,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
559,2019-12-01 00:17:50+00:00,purchase,4607,1487580010796548183,NaN,runail,0.38,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
560,2019-12-01 00:17:50+00:00,purchase,4640,1487580011157258342,NaN,runail,0.37,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
561,2019-12-01 00:17:50+00:00,purchase,4689,1487580010796548183,NaN,runail,0.38,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
562,2019-12-01 00:17:50+00:00,purchase,4768,1487580010796548183,NaN,runail,0.38,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
563,2019-12-01 00:17:50+00:00,purchase,4820,1487580010796548183,NaN,runail,0.38,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
564,2019-12-01 00:17:50+00:00,purchase,4870,1487580010796548183,NaN,runail,0.38,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
565,2019-12-01 00:17:50+00:00,purchase,5762834,1783999071325782053,NaN,Unknown Brand,0.41,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
566,2019-12-01 00:17:50+00:00,purchase,5811642,1487580010872045658,NaN,irisk,0.79,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
567,2019-12-01 00:17:50+00:00,purchase,5843557,1783999071199952917,NaN,Unknown Brand,0.48,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
568,2019-12-01 00:17:50+00:00,purchase,5843567,1783999071199952917,NaN,Unknown Brand,0.48,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
569,2019-12-01 00:17:50+00:00,purchase,5858911,1783999071199952917,NaN,Unknown Brand,0.79,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
570,2019-12-01 00:17:50+00:00,purchase,5887055,1487580010100293687,NaN,jessnail,1.10,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
571,2019-12-01 00:17:50+00:00,purchase,5894905,1487580010100293687,NaN,jessnail,1.10,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
572,2019-12-01 00:17:50+00:00,purchase,5894906,1487580010100293687,NaN,jessnail,1.10,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
573,2019-12-01 00:17:50+00:00,purchase,5894907,1487580010100293687,NaN,jessnail,1.10,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
574,2019-12-01 00:17:50+00:00,purchase,5894908,1487580010100293687,NaN,jessnail,1.10,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
575,2019-12-01 00:17:50+00:00,purchase,5894910,1487580010100293687,NaN,jessnail,1.10,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9
576,2019-12-01 00:17:50+00:00,purchase,5894911,1487580010100293687,NaN,jessnail,1.10,473613801,d1e90c6a-c030-4d06-aaaf-6d12ec502bb9

In [47]:
df['category_code'].value_counts(dropna=False)

category_code
NaN                                       3292700
appliances.environment.vacuum               25299
stationery.cartrige                          8985
apparel.glove                                7875
accessories.bag                              4890
furniture.living_room.cabinet                4402
furniture.bathroom.bath                      3406
appliances.personal.hair_cutter              1083
accessories.cosmetic_bag                      676
appliances.environment.air_conditioner         90
furniture.living_room.chair                    20
Name: count, dtype: int64

In [48]:
df['category_code'].value_counts(dropna=False).head(20)

category_code
NaN                                       3292700
appliances.environment.vacuum               25299
stationery.cartrige                          8985
apparel.glove                                7875
accessories.bag                              4890
furniture.living_room.cabinet                4402
furniture.bathroom.bath                      3406
appliances.personal.hair_cutter              1083
accessories.cosmetic_bag                      676
appliances.environment.air_conditioner         90
furniture.living_room.chair                    20
Name: count, dtype: int64

In [49]:
df['category_code']=df['category_code'].fillna('Unknown')

In [50]:
df['category_code'].value_counts(dropna=False)

category_code
Unknown                                   3292700
appliances.environment.vacuum               25299
stationery.cartrige                          8985
apparel.glove                                7875
accessories.bag                              4890
furniture.living_room.cabinet                4402
furniture.bathroom.bath                      3406
appliances.personal.hair_cutter              1083
accessories.cosmetic_bag                      676
appliances.environment.air_conditioner         90
furniture.living_room.chair                    20
Name: count, dtype: int64

In [51]:
df.groupby('event_type')['price'].mean()

event_type
cart                 5.291491
purchase             5.055548
remove_from_cart     5.366879
view                12.644299
Name: price, dtype: float64

In [52]:
df.groupby('event_type')['price'].agg(['mean','min','max'])

                       mean    min     max
event_type
cart               5.291491   0.00  327.78
purchase           5.055548 -79.37  327.78
remove_from_cart   5.366879   0.00  327.78
view              12.644299   0.00  327.78

In [53]:
df[df['price']<0].shape

(17, 9)

In [54]:
df[df['price']<0].head(20)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
693061,2019-12-06 08:44:06+00:00,purchase,5670257,1487580014042939619,Unknown,Unknown Brand,-15.87,410016187,2414f145-f7fa-473f-9d74-41e5694178a0
942049,2019-12-08 12:38:35+00:00,purchase,5670257,1487580014042939619,Unknown,Unknown Brand,-15.87,579811230,001d3051-07af-1cef-f5e4-10443d9742b9
1633142,2019-12-13 08:44:49+00:00,purchase,5716859,1487580014042939619,Unknown,Unknown Brand,-47.62,414087247,6617078d-899a-4b89-8538-b70e505bff38
1667368,2019-12-13 13:48:10+00:00,purchase,5716857,1487580014042939619,Unknown,Unknown Brand,-23.81,584773479,a3f156d9-b7fc-444d-8899-920715cca75d
2143701,2019-12-17 10:37:03+00:00,purchase,5670257,1487580014042939619,Unknown,Unknown Brand,-15.87,584498077,ecbf0f7c-3c10-42e8-9af6-1397b5428afa
2143702,2019-12-17 10:37:03+00:00,purchase,5716855,1487580014042939619,Unknown,Unknown Brand,-7.94,584498077,ecbf0f7c-3c10-42e8-9af6-1397b5428afa
2164651,2019-12-17 13:31:01+00:00,purchase,5670257,1487580014042939619,Unknown,Unknown Brand,-15.87,513455730,efd60b1a-f616-4f48-a5d2-1a1ab0bd61e1
2548146,2019-12-20 17:56:16+00:00,purchase,5716859,1487580014042939619,Unknown,Unknown Brand,-47.62,589538798,094f5f94-e7d2-4d05-a722-dbc2015c0351
2754627,2019-12-22 19:31:01+00:00,purchase,5716859,1487580014042939619,Unknown,Unknown Brand,-47.62,590958276,42953b86-32c5-4861-8760-e9c2cd35a609
3053899,2019-12-25 13:01:21+00:00,purchase,5716861,1487580014042939619,Unknown,Unknown Brand,-79.37,489184067,af1b35db-1024-495e-8c42-b959491ba136
3098833,2019-12-25 20:37:02+00:00,purchase,5716857,1487580014042939619,Unknown,Unknown Brand,-23.81,592544594,3ffbc078-7722-48b8-91ec-ecf6cac5b1ce
3220372,2019-12-27 08:34:06+00:00,purchase,5670257,1487580014042939619,Unknown,Unknown Brand,-15.87,588438828,0ac59395-6819-49c6-9750-598d45cd71a0
3295546,2019-12-28 07:32:52+00:00,purchase,5716859,1487580014042939619,Unknown,Unknown Brand,-47.62,545859098,013568f6-b7de-4f28-b4e3-e3206527c700
3295882,2019-12-28 07:39:08+00:00,purchase,5670257,1487580014042939619,Unknown,Unknown Brand,-15.87,410016187,55e52759-6ece-4573-b0ae-58031283209e
3328682,2019-12-28 15:42:00+00:00,purchase,5716855,1487580014042939619,Unknown,Unknown Brand,-7.94,539714006,e1d8e3b7-1309-475b-aaaa-4a12ac841c3e
3403149,2019-12-29 14:30:17+00:00,purchase,5716861,1487580014042939619,Unknown,Unknown Brand,-79.37,489118334,da505a6f-d98d-4284-84ba-cc1873f5f8ad
3418052,2019-12-29 17:49:32+00:00,purchase,5670257,1487580014042939619,Unknown,Unknown Brand,-15.87,594077054,bf35396d-126d-4d6f-9f80-cd2eb0dd8a06

In [55]:
df.shape

(3349426, 9)

# Altered the Dataframe (mistakenly)

In [56]:
df=df['price']>=0

In [57]:
type(df)

pandas.Series

In [58]:
df.shape

(3349426,)

# Perform the steps again quickly
# Read .csv Dataset ()
Check - info, shape, head, columns, describe ()

In [59]:
df=pd.read_csv(r'../data/raw/Dataset Dec 2019.csv')

In [60]:
df.shape

(3533286, 9)

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3533286 entries, 0 to 3533285
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     str
 1   event_type     str
 2   product_id     int64
 3   category_id    int64
 4   category_code  str
 5   brand          str
 6   price          float64
 7   user_id        int64
 8   user_session   str
dtypes: float64(1), int64(3), str(5)
memory usage: 242.6 MB

In [62]:
df.columns

Index(['event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='str')

In [63]:
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-12-01 00:00:00 UTC,remove_from_cart,5712790,1487580005268456287,NaN,f.o.x,6.27,576802932,51d85cb0-897f-48d2-918b-ad63965c12dc
1,2019-12-01 00:00:00 UTC,view,5764655,1487580005411062629,NaN,cnd,29.05,412120092,8adff31e-2051-4894-9758-224bfa8aec18
2,2019-12-01 00:00:02 UTC,cart,4958,1487580009471148064,NaN,runail,1.19,494077766,c99a50e8-2fac-4c4d-89ec-41c05f114554
3,2019-12-01 00:00:05 UTC,view,5848413,1487580007675986893,NaN,freedecor,0.79,348405118,722ffea5-73c0-4924-8e8f-371ff8031af4
4,2019-12-01 00:00:07 UTC,view,5824148,1487580005511725929,NaN,NaN,5.56,576005683,28172809-7e4a-45ce-bab0-5efa90117cd5

# Change the data type of 'Event_Time'

In [64]:
df['event_time'] = pd.to_datetime(df['event_time'])

In [65]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3533286 entries, 0 to 3533285
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     datetime64[us, UTC]
 1   event_type     str
 2   product_id     int64
 3   category_id    int64
 4   category_code  str
 5   brand          str
 6   price          float64
 7   user_id        int64
 8   user_session   str
dtypes: datetime64[us, UTC](1), float64(1), int64(3), str(4)
memory usage: 242.6 MB

In [66]:
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-12-01 00:00:00+00:00,remove_from_cart,5712790,1487580005268456287,NaN,f.o.x,6.27,576802932,51d85cb0-897f-48d2-918b-ad63965c12dc
1,2019-12-01 00:00:00+00:00,view,5764655,1487580005411062629,NaN,cnd,29.05,412120092,8adff31e-2051-4894-9758-224bfa8aec18
2,2019-12-01 00:00:02+00:00,cart,4958,1487580009471148064,NaN,runail,1.19,494077766,c99a50e8-2fac-4c4d-89ec-41c05f114554
3,2019-12-01 00:00:05+00:00,view,5848413,1487580007675986893,NaN,freedecor,0.79,348405118,722ffea5-73c0-4924-8e8f-371ff8031af4
4,2019-12-01 00:00:07+00:00,view,5824148,1487580005511725929,NaN,NaN,5.56,576005683,28172809-7e4a-45ce-bab0-5efa90117cd5

In [67]:
df.describe()

         product_id   category_id         price       user_id
count  3.533286e+06  3.533286e+06  3.533286e+06  3.533286e+06
mean   5.473054e+06  1.555023e+18  8.871856e+00  5.223318e+08
std    1.331331e+06  1.689262e+17  1.986474e+01  8.494819e+07
min    3.752000e+03  1.487580e+18 -7.937000e+01  1.180452e+06
25%    5.726191e+06  1.487580e+18  2.060000e+00  4.866830e+08
50%    5.811429e+06  1.487580e+18  4.210000e+00  5.566496e+08
75%    5.859462e+06  1.487580e+18  7.140000e+00  5.828019e+08
max    5.917178e+06  2.235524e+18  3.277800e+02  5.954145e+08

# Check & Remove Duplicates

In [68]:
df.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
3533281    False
3533282    False
3533283    False
3533284    False
3533285    False
Length: 3533286, dtype: bool

In [69]:
df.duplicated().sum()

np.int64(183860)

In [70]:
duplicates = df[df.duplicated()]

In [71]:
duplicates.head(10)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
37,2019-12-01 00:01:52+00:00,cart,5700046,1487580009286598681,NaN,runail,0.40,576802932,51d85cb0-897f-48d2-918b-ad63965c12dc
55,2019-12-01 00:02:49+00:00,cart,5693501,1487580009445982239,NaN,NaN,0.60,579751441,8de492d7-0937-47ae-be2c-a7615aec2b0d
61,2019-12-01 00:03:08+00:00,remove_from_cart,5859482,1487580005671109489,NaN,masura,1.60,561162056,39cf2227-03ed-421e-9615-7814b9b3c5e6
62,2019-12-01 00:03:08+00:00,remove_from_cart,5839671,1487580005671109489,NaN,masura,2.19,561162056,39cf2227-03ed-421e-9615-7814b9b3c5e6
66,2019-12-01 00:03:10+00:00,remove_from_cart,5859482,1487580005671109489,NaN,masura,1.60,561162056,39cf2227-03ed-421e-9615-7814b9b3c5e6
69,2019-12-01 00:03:13+00:00,remove_from_cart,5830501,1487580005671109489,NaN,masura,3.67,561162056,39cf2227-03ed-421e-9615-7814b9b3c5e6
92,2019-12-01 00:03:49+00:00,remove_from_cart,5899853,2115334439910245200,NaN,NaN,4.46,579950721,f39acf4b-11d5-479d-84a7-04f5bc6255ce
94,2019-12-01 00:03:52+00:00,remove_from_cart,5884031,1487580008347075566,NaN,NaN,3.97,579950721,f39acf4b-11d5-479d-84a7-04f5bc6255ce
105,2019-12-01 00:04:02+00:00,remove_from_cart,5884086,1487580005092295511,NaN,NaN,4.75,579950721,f39acf4b-11d5-479d-84a7-04f5bc6255ce
308,2019-12-01 00:09:50+00:00,cart,5790687,1487580009445982239,NaN,nitrimax,3.97,579751441,8de492d7-0937-47ae-be2c-a7615aec2b0d

In [72]:
df[df.duplicated(keep=False)].sort_values(by='user_id').head(20)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
2516381,2019-12-20 11:54:30+00:00,cart,5769907,1487580013841613016,NaN,kapous,3.65,12055855,98b129c4-2ab1-4e89-8511-de4bf7f0d943
2516374,2019-12-20 11:54:29+00:00,cart,5769907,1487580013841613016,NaN,kapous,3.65,12055855,98b129c4-2ab1-4e89-8511-de4bf7f0d943
2516375,2019-12-20 11:54:29+00:00,cart,5769907,1487580013841613016,NaN,kapous,3.65,12055855,98b129c4-2ab1-4e89-8511-de4bf7f0d943
2516371,2019-12-20 11:54:26+00:00,cart,5769907,1487580013841613016,NaN,kapous,3.65,12055855,98b129c4-2ab1-4e89-8511-de4bf7f0d943
2516382,2019-12-20 11:54:30+00:00,cart,5769907,1487580013841613016,NaN,kapous,3.65,12055855,98b129c4-2ab1-4e89-8511-de4bf7f0d943
2516370,2019-12-20 11:54:26+00:00,cart,5769907,1487580013841613016,NaN,kapous,3.65,12055855,98b129c4-2ab1-4e89-8511-de4bf7f0d943
3203562,2019-12-27 01:26:23+00:00,remove_from_cart,5769849,1487580010318397504,NaN,estel,4.29,31156111,7298d4e4-4bbb-4d4f-9cca-c990eedd64c3
3203518,2019-12-27 01:24:02+00:00,remove_from_cart,5677417,1487580010318397504,NaN,estel,6.75,31156111,7298d4e4-4bbb-4d4f-9cca-c990eedd64c3
1358883,2019-12-11 09:47:46+00:00,remove_from_cart,5887963,2130081478220972046,NaN,NaN,8.87,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358814,2019-12-11 09:47:13+00:00,remove_from_cart,5844009,1487580010318397504,NaN,NaN,5.16,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358812,2019-12-11 09:47:13+00:00,remove_from_cart,5844009,1487580010318397504,NaN,NaN,5.16,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
3203188,2019-12-27 01:02:53+00:00,remove_from_cart,5841718,1487580008187692007,NaN,NaN,1.37,31156111,7298d4e4-4bbb-4d4f-9cca-c990eedd64c3
3203390,2019-12-27 01:16:57+00:00,remove_from_cart,5808547,1487580008313521133,NaN,kapous,3.81,31156111,7298d4e4-4bbb-4d4f-9cca-c990eedd64c3
3203563,2019-12-27 01:26:23+00:00,remove_from_cart,5769849,1487580010318397504,NaN,estel,4.29,31156111,7298d4e4-4bbb-4d4f-9cca-c990eedd64c3
1358730,2019-12-11 09:46:42+00:00,remove_from_cart,5862225,1487580008246412266,NaN,matrix,9.84,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358731,2019-12-11 09:46:42+00:00,remove_from_cart,5862225,1487580008246412266,NaN,matrix,9.84,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358869,2019-12-11 09:47:43+00:00,remove_from_cart,5887958,2130081478220972046,NaN,NaN,8.87,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358868,2019-12-11 09:47:42+00:00,remove_from_cart,5887959,2130081478220972046,NaN,NaN,8.87,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358764,2019-12-11 09:46:56+00:00,remove_from_cart,5710657,1487580008246412266,NaN,latinoil,26.19,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096
1358765,2019-12-11 09:46:56+00:00,remove_from_cart,5710657,1487580008246412266,NaN,latinoil,26.19,31156111,dca601b2-e0d5-4538-b95c-3b47e02d0096

In [73]:
df = df.drop_duplicates()

In [74]:
df.shape

(3349426, 9)

In [75]:
duplicates.shape

(183860, 9)

In [76]:
df.duplicated().sum()

np.int64(0)

# Check for NULL Values & fill it with Unknown wherever necessary

In [77]:
df.isnull()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,False,False,False,False,True,False,False,False,False
1,False,False,False,False,True,False,False,False,False
2,False,False,False,False,True,False,False,False,False
3,False,False,False,False,True,False,False,False,False
4,False,False,False,False,True,True,False,False,False
...,...,...,...,...,...,...,...,...,...
3533281,False,False,False,False,True,False,False,False,False
3533282,False,False,False,False,True,False,False,False,False
3533283,False,False,False,False,True,True,False,False,False
3533284,False,False,False,False,True,True,False,False,False
3533285,False,False,False,False,True,True,False,False,False

In [78]:
df.isnull().sum()

event_time             0
event_type             0
product_id             0
category_id            0
category_code    3292700
brand            1428211
price                  0
user_id                0
user_session         714
dtype: int64

In [79]:
df.isnull().sum()/len(df)*100

event_time        0.000000
event_type        0.000000
product_id        0.000000
category_id       0.000000
category_code    98.306396
brand            42.640470
price             0.000000
user_id           0.000000
user_session      0.021317
dtype: float64

In [80]:
purchase_null_brand = df[(df['event_type']=='purchase') & (df['brand'].isnull())]

In [81]:
purchase_null_brand.shape

(91655, 9)

In [82]:
df['brand']=df['brand'].fillna('Unknown Brand')

In [83]:
df['brand'].isnull().sum()

np.int64(0)

In [84]:
df['category_code'].head(10)

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
Name: category_code, dtype: str

In [85]:
df['category_code'].value_counts(dropna=False)

category_code
NaN                                       3292700
appliances.environment.vacuum               25299
stationery.cartrige                          8985
apparel.glove                                7875
accessories.bag                              4890
furniture.living_room.cabinet                4402
furniture.bathroom.bath                      3406
appliances.personal.hair_cutter              1083
accessories.cosmetic_bag                      676
appliances.environment.air_conditioner         90
furniture.living_room.chair                    20
Name: count, dtype: int64

In [86]:
purchase_category_null=df[(df['event_type']=='purchase') & (df['category_code'].isnull())]

In [87]:
purchase_category_null.shape

(210364, 9)

In [88]:
df.loc[(df['event_type']=='purchase') & (df['category_code'].isnull()),'category_code']='Unknown'

In [89]:
purchase_category_null.shape

(210364, 9)

In [90]:
df[(df['event_type']=='purchase') & (df['category_code'].isnull())].shape

(0, 9)

In [91]:
df['category_code'].value_counts(dropna=False)

category_code
NaN                                       3082336
Unknown                                    210364
appliances.environment.vacuum               25299
stationery.cartrige                          8985
apparel.glove                                7875
accessories.bag                              4890
furniture.living_room.cabinet                4402
furniture.bathroom.bath                      3406
appliances.personal.hair_cutter              1083
accessories.cosmetic_bag                      676
appliances.environment.air_conditioner         90
furniture.living_room.chair                    20
Name: count, dtype: int64

# Check Negative Price Values

In [92]:
df.groupby('event_type')['price'].agg(['mean','min','max'])

                       mean    min     max
event_type
cart               5.291491   0.00  327.78
purchase           5.055548 -79.37  327.78
remove_from_cart   5.366879   0.00  327.78
view              12.644299   0.00  327.78

In [93]:
df[df['price']<0].shape

(17, 9)

In [94]:
df[df['price']<0].head(20)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
693061,2019-12-06 08:44:06+00:00,purchase,5670257,1487580014042939619,Unknown,Unknown Brand,-15.87,410016187,2414f145-f7fa-473f-9d74-41e5694178a0
942049,2019-12-08 12:38:35+00:00,purchase,5670257,1487580014042939619,Unknown,Unknown Brand,-15.87,579811230,001d3051-07af-1cef-f5e4-10443d9742b9
1633142,2019-12-13 08:44:49+00:00,purchase,5716859,1487580014042939619,Unknown,Unknown Brand,-47.62,414087247,6617078d-899a-4b89-8538-b70e505bff38
1667368,2019-12-13 13:48:10+00:00,purchase,5716857,1487580014042939619,Unknown,Unknown Brand,-23.81,584773479,a3f156d9-b7fc-444d-8899-920715cca75d
2143701,2019-12-17 10:37:03+00:00,purchase,5670257,1487580014042939619,Unknown,Unknown Brand,-15.87,584498077,ecbf0f7c-3c10-42e8-9af6-1397b5428afa
2143702,2019-12-17 10:37:03+00:00,purchase,5716855,1487580014042939619,Unknown,Unknown Brand,-7.94,584498077,ecbf0f7c-3c10-42e8-9af6-1397b5428afa
2164651,2019-12-17 13:31:01+00:00,purchase,5670257,1487580014042939619,Unknown,Unknown Brand,-15.87,513455730,efd60b1a-f616-4f48-a5d2-1a1ab0bd61e1
2548146,2019-12-20 17:56:16+00:00,purchase,5716859,1487580014042939619,Unknown,Unknown Brand,-47.62,589538798,094f5f94-e7d2-4d05-a722-dbc2015c0351
2754627,2019-12-22 19:31:01+00:00,purchase,5716859,1487580014042939619,Unknown,Unknown Brand,-47.62,590958276,42953b86-32c5-4861-8760-e9c2cd35a609
3053899,2019-12-25 13:01:21+00:00,purchase,5716861,1487580014042939619,Unknown,Unknown Brand,-79.37,489184067,af1b35db-1024-495e-8c42-b959491ba136
3098833,2019-12-25 20:37:02+00:00,purchase,5716857,1487580014042939619,Unknown,Unknown Brand,-23.81,592544594,3ffbc078-7722-48b8-91ec-ecf6cac5b1ce
3220372,2019-12-27 08:34:06+00:00,purchase,5670257,1487580014042939619,Unknown,Unknown Brand,-15.87,588438828,0ac59395-6819-49c6-9750-598d45cd71a0
3295546,2019-12-28 07:32:52+00:00,purchase,5716859,1487580014042939619,Unknown,Unknown Brand,-47.62,545859098,013568f6-b7de-4f28-b4e3-e3206527c700
3295882,2019-12-28 07:39:08+00:00,purchase,5670257,1487580014042939619,Unknown,Unknown Brand,-15.87,410016187,55e52759-6ece-4573-b0ae-58031283209e
3328682,2019-12-28 15:42:00+00:00,purchase,5716855,1487580014042939619,Unknown,Unknown Brand,-7.94,539714006,e1d8e3b7-1309-475b-aaaa-4a12ac841c3e
3403149,2019-12-29 14:30:17+00:00,purchase,5716861,1487580014042939619,Unknown,Unknown Brand,-79.37,489118334,da505a6f-d98d-4284-84ba-cc1873f5f8ad
3418052,2019-12-29 17:49:32+00:00,purchase,5670257,1487580014042939619,Unknown,Unknown Brand,-15.87,594077054,bf35396d-126d-4d6f-9f80-cd2eb0dd8a06

In [95]:
df=df[df['price']>=0]

In [96]:
df[df['price']<0].head(20)

Empty DataFrame
Columns: [event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session]
Index: []

In [97]:
df['price'].describe()

count    3.349409e+06
mean     9.081727e+00
std      2.024991e+01
min      0.000000e+00
25%      2.060000e+00
50%      4.270000e+00
75%      7.140000e+00
max      3.277800e+02
Name: price, dtype: float64

# Inspect Highest Priced Products

In [98]:
df.sort_values(by='price', ascending=False).head(20)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
1474226,2019-12-12 04:49:00+00:00,cart,5906221,1487580006300255120,NaN,strong,327.78,585652841,0e50f83a-78db-4522-82e6-d3fb605553e5
1474238,2019-12-12 04:49:06+00:00,cart,5906221,1487580006300255120,NaN,strong,327.78,585652841,0e50f83a-78db-4522-82e6-d3fb605553e5
758714,2019-12-06 18:43:12+00:00,remove_from_cart,5906221,1487580006300255120,NaN,strong,327.78,526364208,2f264aa9-70c5-46fb-bdb6-a617df0e5116
758515,2019-12-06 18:41:36+00:00,view,5906221,1487580006300255120,NaN,strong,327.78,526364208,2f264aa9-70c5-46fb-bdb6-a617df0e5116
758432,2019-12-06 18:41:04+00:00,cart,5906221,1487580006300255120,NaN,strong,327.78,526364208,2f264aa9-70c5-46fb-bdb6-a617df0e5116
1650119,2019-12-13 11:09:07+00:00,view,5906221,1487580006300255120,NaN,strong,327.78,542652343,4e2d97af-21c9-5b97-aa72-523d102e40b8
190470,2019-12-02 13:12:02+00:00,view,5906221,1487580006300255120,NaN,strong,327.78,580854673,8fa1b869-23d8-4b45-a680-e7f3f1686943
758456,2019-12-06 18:41:17+00:00,cart,5906221,1487580006300255120,NaN,strong,327.78,526364208,2f264aa9-70c5-46fb-bdb6-a617df0e5116
758404,2019-12-06 18:40:49+00:00,cart,5906221,1487580006300255120,NaN,strong,327.78,526364208,2f264aa9-70c5-46fb-bdb6-a617df0e5116
2806963,2019-12-23 10:07:47+00:00,view,5906221,1487580006300255120,NaN,strong,327.78,559709970,7a968d81-091f-42c0-ab12-c50e67be2d1a
758340,2019-12-06 18:40:12+00:00,view,5906221,1487580006300255120,NaN,strong,327.78,526364208,2f264aa9-70c5-46fb-bdb6-a617df0e5116
758386,2019-12-06 18:40:36+00:00,cart,5906221,1487580006300255120,NaN,strong,327.78,526364208,2f264aa9-70c5-46fb-bdb6-a617df0e5116
2408687,2019-12-19 12:07:01+00:00,view,5906221,1487580006300255120,NaN,strong,327.78,518592444,689acb26-2bf2-4abd-a59f-ebfe802209e9
702712,2019-12-06 10:04:45+00:00,view,5906221,1487580006300255120,NaN,strong,327.78,577708899,48de07ad-9d8e-41e3-b19e-7dff08fc776b
1478352,2019-12-12 05:51:56+00:00,view,5906221,1487580006300255120,NaN,strong,327.78,477099991,4bbc4690-4257-4230-b87c-5654285edd0a
1479518,2019-12-12 06:03:46+00:00,view,5906221,1487580006300255120,NaN,strong,327.78,585586094,6dbe8d40-30ad-418c-9e08-a9bfbea1e9b6
834181,2019-12-07 13:16:52+00:00,view,5906221,1487580006300255120,NaN,strong,327.78,530170857,d4406ea5-0979-47f3-88ff-1e59d35e2b1b
2395656,2019-12-19 10:24:49+00:00,view,5906221,1487580006300255120,NaN,strong,327.78,409024587,94ae9142-2a7c-4ba1-89c0-110ecd3541a5
834076,2019-12-07 13:15:56+00:00,view,5906221,1487580006300255120,NaN,strong,327.78,583355285,5d0784f9-974b-47dc-838e-c902db4030b0
722706,2019-12-06 12:58:14+00:00,view,5906221,1487580006300255120,NaN,strong,327.78,439789728,c7cf2e93-e2ef-4db4-84a1-1c7e4ea088c6

# Inspect Unique Users for each Event Type

In [99]:
df['event_type'].value_counts()

event_type
view                1728221
cart                 911641
remove_from_cart     496498
purchase             213049
Name: count, dtype: int64

In [100]:
df['event_type'].value_counts(normalize=True)*100

event_type
view                51.597789
cart                27.217966
remove_from_cart    14.823451
purchase             6.360794
Name: proportion, dtype: float64

In [101]:
df.groupby('event_type')['user_id'].nunique()

event_type
cart                 83458
purchase             25613
remove_from_cart     45217
view                358212
Name: user_id, dtype: int64

# Viewer-to-Purchase Conversion Rate

In [102]:
view_users = df[df['event_type']=='view']['user_id'].nunique()

In [103]:
purchase_users = df[df['event_type']=='purchase']['user_id'].nunique()

In [104]:
view_users

358212

In [105]:
purchase_users

25613

In [106]:
purchase_users / view_users * 100

7.150235056335355